# Generated by Django 3.0.8 on 2020-07-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0004_auto_20200715_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especilidade',
            name='titulo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
