# Generated by Django 3.0.8 on 2020-07-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento: D/M/A')),
                ('direccion', models.CharField(max_length=30, verbose_name='Dirección')),
                ('num_casa', models.CharField(max_length=6, verbose_name='Número de casa')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('prevision', models.CharField(max_length=20)),
                ('enf_cro1', models.CharField(max_length=30)),
                ('enf_cro2', models.CharField(max_length=30)),
                ('enf_cro3', models.CharField(max_length=30)),
            ],
        ),
    ]
