# Generated by Django 3.0.8 on 2020-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registropaciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enf_cro1',
            field=models.CharField(choices=[('01', 'Alzheimer'), ('02', 'Artrítis'), ('03', 'Cáncer'), ('04', 'Depresión'), ('05', 'Diabetes'), ('06', 'Epilepsia'), ('07', 'Esclerosis múltiple'), ('08', 'Hipertensión'), ('09', 'Parkinson'), ('10', 'Tiroides')], default='00', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enf_cro2',
            field=models.CharField(choices=[('01', 'Alzheimer'), ('02', 'Artrítis'), ('03', 'Cáncer'), ('04', 'Depresión'), ('05', 'Diabetes'), ('06', 'Epilepsia'), ('07', 'Esclerosis múltiple'), ('08', 'Hipertensión'), ('09', 'Parkinson'), ('10', 'Tiroides')], default='00', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enf_cro3',
            field=models.CharField(choices=[('01', 'Alzheimer'), ('02', 'Artrítis'), ('03', 'Cáncer'), ('04', 'Depresión'), ('05', 'Diabetes'), ('06', 'Epilepsia'), ('07', 'Esclerosis múltiple'), ('08', 'Hipertensión'), ('09', 'Parkinson'), ('10', 'Tiroides')], default='00', max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('01', 'Fonasa'), ('02', 'Prais'), ('03', 'Consalud'), ('04', 'Cruz blanca'), ('05', 'Colmena'), ('06', 'Mas vida'), ('07', 'Ban Medica')], default='01', max_length=20),
        ),
    ]
