# Generated by Django 3.0.8 on 2020-07-16 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0005_auto_20200715_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('estado', models.CharField(choices=[('0', 'Libre'), ('1', 'Ocupada')], default='0', max_length=1)),
                ('profesional', models.CharField(max_length=20)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.Especilidade')),
            ],
        ),
    ]
