# Generated by Django 3.0.8 on 2020-07-16 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0005_auto_20200715_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('rut_paciente', models.CharField(max_length=10)),
                ('fecha_cita', models.DateTimeField()),
                ('estado', models.CharField(choices=[('0', 'Activa'), ('1', 'Inactiva')], default=None, max_length=1)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.Especilidade')),
            ],
        ),
    ]
