# Generated by Django 3.0.8 on 2020-07-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0005_auto_20200715_1621'),
        ('reservar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidades.Especilidade'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('0', 'Activa'), ('1', 'Inactiva')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_cita',
            field=models.DateTimeField(null=True),
        ),
    ]
