# Generated by Django 3.0.8 on 2020-07-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservar', '0002_auto_20200716_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='especialidad',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
